import {
  FiGithub, FiExternalLink, FiStar, FiZap, FiBook, FiDatabase,
  FiBarChart2, FiGlobe, FiPackage, FiGitPullRequest, FiTerminal,
  FiServer
} from "react-icons/fi";

export const projects = [
  {
    id: 1,
    title: "IRCTC Railway System Clone",
    description: "A comprehensive railway booking system with user authentication, seat selection, payment integration, real-time availability, and admin dashboard built with microservices-ready architecture.",
    shortDescription: "Production-grade railway booking platform with real-time seat selection",
    tech: ["React", "Node.js", "MongoDB", "Express", "JWT", "Redis", "Socket.io"],
    category: "Full Stack",
    subcategory: "MERN Stack",
    github: "https://github.com/ajitdev01/lamp-project/tree/main/IRCTC-Clone",
    liveDemo: "https://github.com/ajitdev01",
    icon: FiServer,
    gradient: "from-blue-500 to-cyan-500",
    features: ["Real-time Booking", "Admin Panel", "Payment Gateway", "Email Notifications", "Seat Selection", "Booking History", "Live Availability"],
    complexity: "Advanced",
    stars: 28,
    lastUpdated: "2 weeks ago",
    highlight: true,
    learningOutcome: "Microservices patterns, real-time updates, transaction management"
  },
  {
    id: 2,
    title: "MERN Full Stack Learning Repository",
    description: "45+ structured lectures covering React, Node.js, Express, MongoDB, and full-stack integration. Includes BiKart e-commerce platform, JWT authentication, Multer file uploads, and MVC architecture patterns.",
    shortDescription: "45+ lectures • E-commerce (BiKart) • JWT Auth • MVC patterns",
    tech: ["React", "Node.js", "Express", "MongoDB", "JWT", "Multer", "Redux", "Tailwind"],
    category: "Full Stack",
    subcategory: "MERN Stack",
    github: "https://github.com/ajitdev01/mern-fullstack",
    liveDemo: "https://github.com/ajitdev01",
    icon: FiBook,
    gradient: "from-purple-500 to-violet-500",
    features: ["45+ Lectures", "BiKart E-commerce", "JWT Auth", "Multer Uploads", "MVC Architecture", "REST APIs", "Production Patterns"],
    complexity: "Advanced",
    stars: 67,
    lastUpdated: "1 week ago",
    highlight: true,
    learningOutcome: "Teaching as mastery — production-ready full stack architecture"
  },
  {
    id: 3,
    title: "LAMP Stack Authentication System",
    description: "Enterprise-ready PHP + MySQL backend with secure authentication, email OTP verification, session management, and complete CRUD operations for internal tools and admin dashboards.",
    shortDescription: "PHP/MySQL enterprise auth with OTP & CRUD",
    tech: ["PHP", "MySQL", "HTML5", "CSS3", "JavaScript", "Nodemailer", "Bootstrap"],
    category: "Full Stack",
    subcategory: "LAMP Stack",
    github: "https://github.com/ajitdev01/lamp-project",
    liveDemo: "https://ajitdev.com",
    icon: FiDatabase,
    gradient: "from-emerald-500 to-teal-500",
    features: ["Secure Authentication", "Email OTP Verification", "Session Management", "CRUD Operations", "Admin Dashboard", "Password Hashing"],
    complexity: "Intermediate",
    stars: 24,
    lastUpdated: "3 weeks ago",
    highlight: false,
    learningOutcome: "Traditional enterprise stack, server-side rendering, legacy system integration"
  },
  {
    id: 4,
    title: "DSA Journey Repository",
    description: "400+ optimized Data Structures & Algorithms solutions with detailed time/space complexity analysis. Daily practice following NeetCode roadmap — Arrays, Trees, Graphs, Recursion, and Dynamic Programming.",
    shortDescription: "400+ LeetCode solutions • Complexity analysis • Daily streak",
    tech: ["C++", "DSA", "STL", "LeetCode", "NeetCode", "VS Code"],
    category: "DSA",
    subcategory: "Problem Solving",
    github: "https://github.com/ajitdev01/DSA-Journey-2026",
    liveDemo: "#",
    icon: FiBarChart2,
    gradient: "from-amber-500 to-orange-500",
    features: ["400+ Solutions", "Complexity Analysis", "Clean Code", "STL Usage", "Pattern Problems", "Competitive Programming", "Weekly Contests"],
    complexity: "Intermediate",
    stars: 82,
    lastUpdated: "4 days ago",
    highlight: true,
    learningOutcome: "Algorithmic thinking — foundation for scalable systems"
  },
  {
    id: 5,
    title: "Next.js SEO-Optimized Blog Platform",
    description: "High-performance blog platform with Next.js SSR/SSG, structured data (JSON-LD), OpenGraph optimization, Core Web Vitals scoring 95+, and automated sitemap generation.",
    shortDescription: "SSR/SSG • Core Web Vitals 95+ • JSON-LD structured data",
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "MDX", "Vercel", "Schema.org"],
    category: "Frontend",
    subcategory: "Next.js",
    github: "#",
    liveDemo: "#",
    icon: FiGlobe,
    gradient: "from-rose-500 to-pink-500",
    features: ["SSR/SSG Hybrid", "JSON-LD Structured Data", "Core Web Vitals 95+", "Automatic Sitemap", "OpenGraph Tags", "MDX Support", "Dark Mode"],
    complexity: "Advanced",
    stars: 41,
    lastUpdated: "2 weeks ago",
    highlight: true,
    learningOutcome: "SEO engineering — ranking apps in competitive markets"
  },
  {
    id: 6,
    title: "BiKart E-commerce Platform",
    description: "Full-featured e-commerce platform with product management, cart system, user reviews, wishlist, payment integration, and order tracking — built as part of the MERN learning series.",
    shortDescription: "Full e-commerce • Cart • Payments • Product management",
    tech: ["React", "Node.js", "MongoDB", "Express", "Redux", "Stripe", "JWT"],
    category: "Full Stack",
    subcategory: "MERN Stack",
    github: "#",
    liveDemo: "#",
    icon: FiPackage,
    gradient: "from-indigo-500 to-blue-500",
    features: ["Product Catalog", "Shopping Cart", "User Reviews", "Wishlist", "Payment Integration", "Order Tracking", "Admin Panel"],
    complexity: "Advanced",
    stars: 53,
    lastUpdated: "2 weeks ago",
    highlight: true,
    learningOutcome: "End-to-end e-commerce — real revenue-ready architecture"
  },
  {
    id: 7,
    title: "DevOps CI/CD Pipeline with GitHub Actions",
    description: "Automated CI/CD pipeline with GitHub Actions for MERN applications — linting, testing, building, and deploying to AWS EC2 with zero-downtime strategies.",
    shortDescription: "GitHub Actions • AWS EC2 • Automated deployment",
    tech: ["GitHub Actions", "AWS EC2", "Docker", "Node.js", "React", "Nginx"],
    category: "DevOps",
    subcategory: "CI/CD",
    github: "#",
    liveDemo: "#",
    icon: FiGitPullRequest,
    gradient: "from-cyan-500 to-blue-500",
    features: ["Automated Testing", "Build Optimization", "Docker Containerization", "AWS EC2 Deployment", "Zero-downtime", "Rollback Strategy", "Monitoring"],
    complexity: "Intermediate",
    stars: 19,
    lastUpdated: "1 month ago",
    highlight: false,
    learningOutcome: "Production deployment automation — DevOps supporting role"
  },
  {
    id: 8,
    title: "Python Automation Scripts Collection",
    description: "Production-ready Python scripts for web scraping, API testing, data processing, file automation, and Linux system administration — used in daily DevOps workflows.",
    shortDescription: "Web scraping • API automation • Data processing",
    tech: ["Python", "Selenium", "Requests", "BeautifulSoup", "Pandas", "Bash"],
    category: "Programming",
    subcategory: "Python",
    github: "https://github.com/ajitdev01/python-core-to-advanced",
    liveDemo: "#",
    icon: FiTerminal,
    gradient: "from-gray-600 to-gray-800",
    features: ["Web Scraping", "API Testing", "Data Processing", "File Automation", "Linux Scripts", "Scheduled Tasks", "Logging"],
    complexity: "Intermediate",
    stars: 27,
    lastUpdated: "3 weeks ago",
    highlight: false,
    learningOutcome: "Automation mindset — efficiency in every workflow"
  }
];
